{% set name = "opencosmo" %}
{% set version = "1.0.2" %}
{% set build_number = 0 %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 95be5214cb8145e7a0c98f54457d5daf995ee7cadc5a6e03e4ab8a78ff1b6d62

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv-build
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=2.0,<2.4
    - h5py
    - pydantic
    - healpy
    - hdf5plugin >=5.0.0,<6.0.0
    - astropy-base >=7.2.0,<8.0.0
    - deprecated
    - click >=8.2.1,<9.0.0
    - numba >=0.62.1
    - rustworkx >=0.17.1
    - healsparse ==1.11.1
    - healpy >=1.18.1,<2.0.0



test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ArgonneCPAC/OpenCosmo
  summary: 'The OpenCosmo Python Toolkit'
  description: |
    The OpenCosmo Python Toolkit provides utilities for reading, writing and manipulating data from cosmological simulations produced by the Cosmolgical Physics and Advanced Computing (CPAC) group at Argonne National Laboratory. The OpenCosmo toolkit integrates with standard tools such as AstroPy, and allows you to manipulate data in a fully-consistent cosmological context.

  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  doc_url: https://opencosmo.readthedocs.org/

extra:
  recipe-maintainers:
    - AstroPatty
