{% set name = "opencosmo" %}
{% set version = "0.9.5" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b13fa5126880835257ee1374eecac8e23aec61b76ba8f6488f84b69fec105726

build:
  noarch: python
  script: pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv-build
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.26
    - h5py
    - pydantic
    - healpy
    - hdf5plugin
    - astropy-base >=7.0.1,<8.0.0
    - deprecated
    - click >=8.2.1,<9.0.0
    - networkx >=3.5,<4.0


test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ArgonneCPAC/OpenCosmo
  summary: 'The OpenCosmo Python Toolkit'
  description: |
    The OpenCosmo Python Toolkit provides utilities for reading, writing and manipulating data from cosmological simulations produced by the Cosmolgical Physics and Advanced Computing (CPAC) group at Argonne National Laboratory. The OpenCosmo toolkit integrates with standard tools such as AstroPy, and allows you to manipulate data in a fully-consistent cosmological context.

  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  doc_url: https://opencosmo.readthedocs.org/

extra:
  recipe-maintainers:
    - AstroPatty
